### ISSUE TITLE
slides not available?

### ISSUE THREAD

**Issue by samumantha** [betterscientificsoftware/swe-cse-bof#6]
Should the pdfs be available behind the links on the agenda of the bof of '22?

**Comment by bernhold** [comment]
@samumantha, I'm sorry I didn't notice this issue in a timely manner.  I need to check my notification subscriptions.

But I can say that the slides for both the [ISC22](https://betterscientificsoftware.github.io/swe-cse-bof/2022-05-isc22-bof/) and [SC22}(https://betterscientificsoftware.github.io/swe-cse-bof/2022-11-sc22-bof/) BoFs are now available, even if there was a problem before.  I apologize if this is too late to be useful to you.

**Comment by bernhold** [comment]
Ah, for the record, I was on vacation and I probably just ignored all of the GitHub notifications I received during that time.  I guess I should be more selective.

**Comment by samumantha** [comment]
Thanks David :)
